<a href="https://colab.research.google.com/github/windrise/basictorch/blob/master/BasicTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 基本环境测试


In [0]:
from __future__ import print_function
import torch

In [0]:
 x = torch.Tensor(5,3)
print(x)


 2.2169e-35  0.0000e+00  4.4842e-44
 0.0000e+00         nan  0.0000e+00
 6.7947e+22  2.6079e+20  6.6383e-07
 1.0514e-05  8.5455e-07  4.1536e-08
 2.1253e-07  8.5013e-07  0.0000e+00
[torch.FloatTensor of size 5x3]



In [0]:
y = torch.rand(5,3)
print(y)
print(y.size)


 0.6284  0.5950  0.2834
 0.2547  0.9488  0.1956
 0.2709  0.5084  0.3546
 0.7146  0.9547  0.8258
 0.6737  0.4501  0.6427
[torch.FloatTensor of size 5x3]

<built-in method size of torch.FloatTensor object at 0x7f1e33021708>


## GPU

In [0]:
import tensorflow as tf
tf.test.gpu_device_name() 

'/device:GPU:0'

In [0]:
!nvidia-smi

Fri Jan  3 06:07:38 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.44       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [0]:
import torch
torch.cuda.is_available()

True

In [0]:
!python -V

Python 3.6.9


## 操作系统信息

In [0]:
!sudo lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic


## 查看cuda版本

In [0]:
!cat /usr/local/cuda/version.txt

CUDA Version 10.0.130


In [0]:
!ls

sample_data


## python

### 变量与对象
对象：内存中存储数据的实体，有明确的类型。一切皆是对象，函数也是对象。  
变量：指向对象的指针，对对象的引用。变量没有类型

In [0]:
# 深浅拷贝
'''
拷贝：原则上就是把数据分离出来，复制其数据，并以后修改互不影响。
先看一个非拷贝的例子
=赋值：数据完全共享（=赋值是在内存中指向同一个对象，如果是可变(mutable)类型，比如列表，修改其中一个，另一个必定改变
如果是不可变类型(immutable),比如字符串，修改了其中一个，另一个并不会变）
'''
import copy
a = [1, 2, [1,2]]
# 直接复制前后没有隔离   共享内存  地址相同
b = a
# 浅拷贝  数据半共享   只成功拷贝第一层
c = copy.copy(a)
d = a[:]
# 深拷贝  前后两个变量完全隔离  数据完全不共享
e = copy.deepcopy(a)
a.append(3)
a[2].append(3)
a,b,c,d,e

([1, 2, [1, 2, 3], 3],
 [1, 2, [1, 2, 3], 3],
 [1, 2, [1, 2, 3]],
 [1, 2, [1, 2, 3]],
 [1, 2, [1, 2]])

### 作用域

### 高阶函数
高阶函数指的是 接受函数作为输入或输出的函数。  
对于python而言，函数是一等对象，既可以赋值给变量、添加到集合中、传参到函数中，也可以作为函数的返回值。  
变量即为对对象的引用。 

### **迭代器和生成器**
> iter(),next(),yield  
> list,dict,set

## 常用工具  
> 版本管理git&github
> python调试器： pdb
> 网页可视化： jupyter
> 分屏工具： Terminator
> 任务托管： Screen 
> 任务后台执行： &nohup

## Tensor

### 数据类型

In [0]:
import torch


In [0]:
# 创建新的Tensor, 默认是torch.FloatTensor类型
a = torch.Tensor(2,2)
a 
#a.type()  #'torch.FloatTensor'

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])

In [0]:
# 使用int()，float()，double()等直接进行数据类型的转换
b = a.double()
b

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]], dtype=torch.float64)

In [0]:
# 使用type()函数
c = a.type(torch.DoubleTensor)
c

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]], dtype=torch.float64)

In [0]:
# 使用type_as()函数
d = a.type_as(b)
d

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]], dtype=torch.float64)

### Tensor的创建和维度查看

* 基础Tensor函数 torch.Tensor(2,2) #(2,2)每一维大小 
* 指定类型 torch.DoubleTensor(2,2)  
* 使用Python的list序列 torch.Tensor([[1,2],[3,4]]) 
* 默认值为0 torch.zeros(2,2)
* 默认值为1 torch.ones(2,2)
* 对角张量 torch.eye(2,2)
* 随机张量 torch.randn(2,2)
* 随机排列张量 torch.randperm(4）

> torch.arange(start,end,step)函数，从start到end,间距为step,一维向量
> torch.linspace(start,end,steps)函数，从start到end,一共steps份，一维向量  
> torch.randperm(num)生成长度为num的随机排列向量  
> pytorch 0.4中增加了torch.tensor()方法，参数可以为Python的list，Numpy的ndarray等

In [0]:
f = torch.eye(2,3)
f

tensor([[1., 0., 0.],
        [0., 1., 0.]])

查看Tensor的维度
> Tensor.shape或者size()函数可以查看 Tensor每一维大小  
查看Tensor的元素总个数
> Tensor.numel()或者Tensor.nelement()函数

### Tensor的组合与分块 
组合： torch.cat(),torch.stack()  
指沿着已有的数据的某一维度进行拼接，其他维度保持一致  
分块： torch.chunk(),torch.split()  
指将Tensor分割成不同的子Tensor，前者需要指定分块的数量，后者需要指定每一个分块的大小

In [0]:
a = torch.Tensor([[1,2],[3,4]])
b = torch.Tensor([[5,6],[7,8]])
a,b

(tensor([[1., 2.],
         [3., 4.]]), tensor([[5., 6.],
         [7., 8.]]))

In [0]:
#以第一维进行拼接，则变成 4x2
torch.cat([a,b],0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [0]:
#以第一维进行拼接，则变成 2x4
torch.cat([a,b],1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [0]:
#以第0维进行stack,叠加的基本单位为序列本身，即为a和b，因此输出[a,b]， 输出维度为 2x2x2
torch.stack([a,b],0)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [0]:
#以第1维进行stack,叠加的基本单位为每一行， 输出维度为 2x2x2
torch.stack([a,b],1)

tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])

In [0]:
#以第2维进行stack,叠加的基本单位为每一行的每一个元素，输出维度为 2x2x2
torch.stack([a,b],2)

tensor([[[1., 5.],
         [2., 6.]],

        [[3., 7.],
         [4., 8.]]])

In [0]:
a = torch.Tensor([[1,2,3],[4,5,6]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [0]:
# 使用chunk,沿着第0维分块，一共分两块， 分成两个1x3的Tensor
torch.chunk(a,2,0)

(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.]]))

In [0]:
# 使用chunk,沿着第1维分块，一共分两块，不能整除是最后一个维数会小于前面的， 分成一个2x2和2x1的Tensor
torch.chunk(a,2,1)

(tensor([[1., 2.],
         [4., 5.]]), tensor([[3.],
         [6.]]))

In [0]:
# 使用split,沿着第0维分块，每一块维度是2，由于第一维维度书总共为2，因此相当于没有分割
torch.split(a,2,0)

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),)

In [0]:
# 使用split,沿着第1维分块，每一块维度是2，分成2x2，2x1
torch.split(a,2,1)

(tensor([[1., 2.],
         [4., 5.]]), tensor([[3.],
         [6.]]))

In [0]:
# split 也可以根据输入的list进行自动分块，list中的元素代表了每一个分块的维度
torch.split(a,[1,2],1)

(tensor([[1.],
         [4.]]), tensor([[2., 3.],
         [5., 6.]]))

### Tensor的索引和变形  
与numpy类似，主要包含下标索引，表达式索引，使用torch.where()和Tensor.clamp()的选择性索引

In [1]:
import torch
a = torch.Tensor([[0,1],[2,3]])
a

tensor([[0., 1.],
        [2., 3.]])

In [2]:
#根据下标索引
a[1],a[0,1]


(tensor([2., 3.]), tensor(1.))

In [3]:
#选择a中大于0 的元素，返回和a相同大小的Tensor，符合条件的置为1，否则置为0；  a>0
#选择符合条件的元素并返回，等价于torch.masked_select(a,a>0)  a[a>0]
a>0,a[a>0]

(tensor([[False,  True],
         [ True,  True]]), tensor([1., 2., 3.]))

In [4]:
#选择非零元素的坐标，并返回
torch.nonzero(a)

tensor([[0, 1],
        [1, 0],
        [1, 1]])

In [5]:
#torch.where(condition,x,y), 满足condition的位置输出x，否则输出y
torch.where(a>1,torch.full_like(a,1),a)

tensor([[0., 1.],
        [1., 1.]])

In [6]:
#对于Tensor元素进行限制可以使用clamp()函数，示例如下，限制最小值为1，最大值为2
a.clamp(1,2)

tensor([[1., 1.],
        [2., 2.]])