<a href="https://colab.research.google.com/github/windrise/basictorch/blob/master/BasicTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 基本环境测试


In [0]:
from __future__ import print_function
import torch

In [0]:
 x = torch.Tensor(5,3)
print(x)


 2.2169e-35  0.0000e+00  4.4842e-44
 0.0000e+00         nan  0.0000e+00
 6.7947e+22  2.6079e+20  6.6383e-07
 1.0514e-05  8.5455e-07  4.1536e-08
 2.1253e-07  8.5013e-07  0.0000e+00
[torch.FloatTensor of size 5x3]



In [0]:
y = torch.rand(5,3)
print(y)
print(y.size)


 0.6284  0.5950  0.2834
 0.2547  0.9488  0.1956
 0.2709  0.5084  0.3546
 0.7146  0.9547  0.8258
 0.6737  0.4501  0.6427
[torch.FloatTensor of size 5x3]

<built-in method size of torch.FloatTensor object at 0x7f1e33021708>


## GPU

In [0]:
import tensorflow as tf
tf.test.gpu_device_name() 

'/device:GPU:0'

In [0]:
!nvidia-smi

Fri Jan  3 06:07:38 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.44       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [0]:
import torch
torch.cuda.is_available()

True

In [0]:
!python -V

Python 3.6.9


## 操作系统信息

In [0]:
!sudo lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic


## 查看cuda版本

In [0]:
!cat /usr/local/cuda/version.txt

CUDA Version 10.0.130


In [0]:
!ls

sample_data


## python

### 变量与对象
对象：内存中存储数据的实体，有明确的类型。一切皆是对象，函数也是对象。  
变量：指向对象的指针，对对象的引用。变量没有类型

In [0]:
# 深浅拷贝
'''
拷贝：原则上就是把数据分离出来，复制其数据，并以后修改互不影响。
先看一个非拷贝的例子
=赋值：数据完全共享（=赋值是在内存中指向同一个对象，如果是可变(mutable)类型，比如列表，修改其中一个，另一个必定改变
如果是不可变类型(immutable),比如字符串，修改了其中一个，另一个并不会变）
'''
import copy
a = [1, 2, [1,2]]
# 直接复制前后没有隔离   共享内存  地址相同
b = a
# 浅拷贝  数据半共享   只成功拷贝第一层
c = copy.copy(a)
d = a[:]
# 深拷贝  前后两个变量完全隔离  数据完全不共享
e = copy.deepcopy(a)
a.append(3)
a[2].append(3)
a,b,c,d,e

([1, 2, [1, 2, 3], 3],
 [1, 2, [1, 2, 3], 3],
 [1, 2, [1, 2, 3]],
 [1, 2, [1, 2, 3]],
 [1, 2, [1, 2]])

### 作用域

### 高阶函数
高阶函数指的是 接受函数作为输入或输出的函数。  
对于python而言，函数是一等对象，既可以赋值给变量、添加到集合中、传参到函数中，也可以作为函数的返回值。  
变量即为对对象的引用。 

### **迭代器和生成器**
> iter(),next(),yield  
> list,dict,set

## 常用工具  
> 版本管理git&github
> python调试器： pdb
> 网页可视化： jupyter
> 分屏工具： Terminator
> 任务托管： Screen 
> 任务后台执行： &nohup

## Tensor

### 数据类型

In [0]:
import torch


In [0]:
# 创建新的Tensor, 默认是torch.FloatTensor类型
a = torch.Tensor(2,2)
a 
#a.type()  #'torch.FloatTensor'

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])

In [0]:
# 使用int()，float()，double()等直接进行数据类型的转换
b = a.double()
b

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]], dtype=torch.float64)

In [0]:
# 使用type()函数
c = a.type(torch.DoubleTensor)
c

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]], dtype=torch.float64)

In [0]:
# 使用type_as()函数
d = a.type_as(b)
d

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]], dtype=torch.float64)

### Tensor的创建和维度查看

* 基础Tensor函数 torch.Tensor(2,2) #(2,2)每一维大小 
* 指定类型 torch.DoubleTensor(2,2)  
* 使用Python的list序列 torch.Tensor([[1,2],[3,4]]) 
* 默认值为0 torch.zeros(2,2)
* 默认值为1 torch.ones(2,2)
* 对角张量 torch.eye(2,2)
* 随机张量 torch.randn(2,2)
* 随机排列张量 torch.randperm(4）

> torch.arange(start,end,step)函数，从start到end,间距为step,一维向量
> torch.linspace(start,end,steps)函数，从start到end,一共steps份，一维向量  
> torch.randperm(num)生成长度为num的随机排列向量  
> pytorch 0.4中增加了torch.tensor()方法，参数可以为Python的list，Numpy的ndarray等

In [0]:
f = torch.eye(2,3)
f

tensor([[1., 0., 0.],
        [0., 1., 0.]])

查看Tensor的维度
> Tensor.shape或者size()函数可以查看 Tensor每一维大小  
查看Tensor的元素总个数
> Tensor.numel()或者Tensor.nelement()函数

### Tensor的组合与分块 
组合： torch.cat(),torch.stack()  
指沿着已有的数据的某一维度进行拼接，其他维度保持一致  
分块： torch.chunk(),torch.split()  
指将Tensor分割成不同的子Tensor，前者需要指定分块的数量，后者需要指定每一个分块的大小

In [0]:
a = torch.Tensor([[1,2],[3,4]])
b = torch.Tensor([[5,6],[7,8]])
a,b

(tensor([[1., 2.],
         [3., 4.]]), tensor([[5., 6.],
         [7., 8.]]))

In [0]:
#以第一维进行拼接，则变成 4x2
torch.cat([a,b],0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [0]:
#以第一维进行拼接，则变成 2x4
torch.cat([a,b],1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [0]:
#以第0维进行stack,叠加的基本单位为序列本身，即为a和b，因此输出[a,b]， 输出维度为 2x2x2
torch.stack([a,b],0)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [0]:
#以第1维进行stack,叠加的基本单位为每一行， 输出维度为 2x2x2
torch.stack([a,b],1)

tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])

In [0]:
#以第2维进行stack,叠加的基本单位为每一行的每一个元素，输出维度为 2x2x2
torch.stack([a,b],2)

tensor([[[1., 5.],
         [2., 6.]],

        [[3., 7.],
         [4., 8.]]])

In [0]:
a = torch.Tensor([[1,2,3],[4,5,6]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [0]:
# 使用chunk,沿着第0维分块，一共分两块， 分成两个1x3的Tensor
torch.chunk(a,2,0)

(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.]]))

In [0]:
# 使用chunk,沿着第1维分块，一共分两块，不能整除是最后一个维数会小于前面的， 分成一个2x2和2x1的Tensor
torch.chunk(a,2,1)

(tensor([[1., 2.],
         [4., 5.]]), tensor([[3.],
         [6.]]))

In [0]:
# 使用split,沿着第0维分块，每一块维度是2，由于第一维维度书总共为2，因此相当于没有分割
torch.split(a,2,0)

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),)

In [0]:
# 使用split,沿着第1维分块，每一块维度是2，分成2x2，2x1
torch.split(a,2,1)

(tensor([[1., 2.],
         [4., 5.]]), tensor([[3.],
         [6.]]))

In [0]:
# split 也可以根据输入的list进行自动分块，list中的元素代表了每一个分块的维度
torch.split(a,[1,2],1)

(tensor([[1.],
         [4.]]), tensor([[2., 3.],
         [5., 6.]]))

### Tensor的索引和变形  
与numpy类似，主要包含下标索引，表达式索引，使用torch.where()和Tensor.clamp()的选择性索引

In [0]:
import torch
a = torch.Tensor([[0,1],[2,3]])
a

tensor([[0., 1.],
        [2., 3.]])

In [0]:
#根据下标索引
a[1],a[0,1]


(tensor([2., 3.]), tensor(1.))

In [0]:
#选择a中大于0 的元素，返回和a相同大小的Tensor，符合条件的置为1，否则置为0；  a>0
#选择符合条件的元素并返回，等价于torch.masked_select(a,a>0)  a[a>0]
a>0,a[a>0]

(tensor([[False,  True],
         [ True,  True]]), tensor([1., 2., 3.]))

In [0]:
#选择非零元素的坐标，并返回
torch.nonzero(a)

tensor([[0, 1],
        [1, 0],
        [1, 1]])

In [0]:
#torch.where(condition,x,y), 满足condition的位置输出x，否则输出y
torch.where(a>1,torch.full_like(a,1),a)

tensor([[0., 1.],
        [1., 1.]])

In [0]:
#对于Tensor元素进行限制可以使用clamp()函数，示例如下，限制最小值为1，最大值为2
a.clamp(1,2)

tensor([[1., 1.],
        [2., 2.]])

Pytorch常用的变形操作

---

| 变形操作 | 功能  |  
| :------:  | :------: |
| view(),resize(),reshape() | 调整Tensor的形状，元素总数相同 |
| transpose(),permute()   | 各维度之间的变换 |
| squeeze(),unsqueeze()   | 处理size为1的维度 |
| expand(),expand_as()   |  复制元素来扩展维度 |  


---



#### 1.view()、resize()、reshape()函数  
view(),resize(),reshape()函数可以在不改变Tensor数据的前提下任意改变Tensor的形状，必须保证调整前后元素总数相同，并且调整前后共享内存，三者的作用基本相同。



In [1]:
import torch
a = torch.arange(1,5)
b = a.view(2,2)
b

tensor([[1, 2],
        [3, 4]])

In [6]:
c = a.reshape(4,1)
c

tensor([[1],
        [2],
        [3],
        [4]])

In [7]:
d = a.resize(4,1)
a,d

/usr/local/lib/python3.6/dist-packages/torch/tensor.py:330: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [8]:
#改变b,c,d,则a也跟着改变
b[0,0]=0
c[1,0]=0
d[2,0]=0
a

tensor([0, 0, 0, 4])

In [9]:
#如果想要直接改变Tensor的尺寸，可以使用resize_()的原地操作函数。在resize_()函数中，如果超出了原Tensor的大小，则重新分配新的内存，
#如果小于原Tensor的大小，则剩余部分隐藏的保留
c = a.resize_(2,3)
c,a

(tensor([[                  0,                   0,                   0],
         [                  4, 8746397786380201545, 7312272888175158610]]),
 tensor([[                  0,                   0,                   0],
         [                  4, 8746397786380201545, 7312272888175158610]]))

#### 2、transpose()和permute()函数
transpose()函数可以将指定的两个维度的元素进行转置，  
而permute()函数则可以按照给定的维度进行维度变换。

In [10]:
a = torch.randn(2,2,2)
a

tensor([[[-0.4759,  1.1461],
         [-0.1048, -0.3149]],

        [[ 0.2218,  1.1860],
         [ 0.7640,  2.3186]]])

In [0]:
#将第0维和第1维的元素进行转置
a.transpose(0,1)

In [23]:
#按照第2,1,0 的顺序重新进行元素排列
a[1,0,0]

tensor(0.2218)

In [0]:
b = a.permute(2,1,0)

In [24]:
b[0,0,1]

tensor(0.2218)

#### 3、squeeze()和unsqueeze()函数  
两者传入的参数都表示要处理的tensor的维度。  
前者用于去除size为1的维度，也即--降维，而后者则是将指定的维度的size变为1，也即--升维，其中的参数是指定增加维度的位置.

In [38]:
a = torch.arange(0,6)
b = a.view(2,3)
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [39]:
#在第二维增加一个维度，使其维度变为（2,1,3） 
b.unsqueeze(1).shape

torch.Size([2, 1, 3])

In [41]:
#先得到一个维度为（1,2,3）的tensor
c = b.unsqueeze(0)
c.shape

torch.Size([1, 2, 3])

In [43]:
#使用squeeze()函数将第一维去掉
c.squeeze(-3),c.squeeze(-3).shape

(tensor([[0, 1, 2],
         [3, 4, 5]]), torch.Size([2, 3]))

In [44]:
#可以看出维度并没有变化，仍然为（1，2，3），这是因为只有维度为1时才会起作用
c.squeeze(-2).shape

torch.Size([1, 2, 3])

#### 4、expand()和expand_as()函数
有时候需要采用复制元素的形式来扩展Tensor的维度，这时expand就派上了用场。expand()函数将size=1的维度复制扩展为指定大小，也可以使用expand_as()函数指定为是特定Tensor的维度。

### Tensor的内存共享
* 通过Tensor初始化Tensor：  
通过Tensor初始化另一个Tensor或者通过Tensor的组合，分块，索引，变形操作来初始化另一个Tensor，则这两个Tensor共享内存
* 原地操作符：  
pytorch对于一些操作通过加后缀'\_'实现了原地操作，如add\_()和resize_()操作,即本身的Tensor会改变
* Tensor和Numpy转换：  
Tensor和Numpy可以高效的进行转换，并且转换前后的变量共享内存。甚至可以曲线救国。。。。


In [6]:
#原地操作符
a = torch.Tensor([[1,2],[3,4]])
b = a.add_(a)
a

tensor([[2., 4.],
        [6., 8.]])

In [7]:
#曲线就救国
a = torch.randn(1,2)
a 

tensor([[0.3152, 0.4635]])

In [8]:
#将Tensor转换为numpy
b = a.numpy()
b

array([[0.31517386, 0.46351725]], dtype=float32)

In [9]:
#将numpy转换为Tensor
c = torch.from_numpy(b)
#Tensor转化为list
d = a.tolist()
c,d

(tensor([[0.3152, 0.4635]]), [[0.315173864364624, 0.4635172486305237]])

## Autograd与计算图
pytorch 0.4版本将Tensor与Variable进行了整合

> 通过requires_grad参数创建支持自动求导的Tensor  
> 默认为false，设置为True则需要求导。

**Tensor有两种重要属性，分别记录了该Tensor的梯度和经历的操作**
* grad： 该Tensor对应的梯度，类型为Tensor，并且与Tensor同维度。
* grad_fn: 指向function对象，即该Tensor经过了什么样的操作，用作反向传播的梯度计算，如果该Tensor由用户创建，则该grad_fn为None

In [1]:
import torch
a = torch.randn(2,2,requires_grad=True)
b = torch.randn(2,2)
a.requires_grad,b.requires_grad

(True, False)

In [2]:
#也可以通过内置函数 requires_grad_()将Tensor变为需要求导
b.requires_grad_()

tensor([[-0.0782,  1.2187],
        [ 0.1011, -0.9570]], requires_grad=True)

In [3]:
#通过计算生产的Tensor，由于依赖的Tensor需要求导，因此c也需要求导
c = a + b
c.requires_grad

True

In [4]:
# a与b是自己创建的， grad_fn是None,而c的是一个Add函数创建的
a.grad_fn,b.grad_fn,c.grad_fn

(None, None, <AddBackward0 at 0x7f8302fd1278>)

PyTorch0.4中，.data 仍保留，但建议使用 .detach(), 区别在于 .data 返回和 x 的相同数据 tensor, 但不会加入到x的计算历史里，且require s_grad = False, 这样有些时候是不安全的, 因为 x.data 不能被 autograd 追踪求微分 。 .detach() 返回相同数据的 tensor ,且 requires_grad=False ,但能通过 in-place 操作报告给 autograd 在进行反向传播的时候.


In [5]:
#注意： 早些版本使用.data属性来获取数据，Pytorch0.4建议使用Tensor.detach()函数，因为.data属性在某型情况下不安全，原因在于对
#.data生成的数据进行修改不会被 autograd追踪。Tensor.detach()函数生成的数据默认requires.grad 为false
d = c.detach()
d.requires_grad

False

### Autograd注意事项：
动态图特性：  练习中自己感受  
backward()函数还有一个需要传入的参数 grad_variabels,其代表了根节点的导数，也可以看作根节点各部分的权重系。因为Pytorch不支持Tensor对Tensor求导，求导是都是标量对于Tensor进行求导，因此如果根节点是向量，则应配以对应大小的权重，并求和得到标量，再反传。如果根节点的值是标量则参数可以省略，默认为1.  
当有多个输出需要同时进行梯度反传时，需要将retain_graph设置为True，从而保证在计算多个输出的梯度时互不影响。

## 神经网络工具箱 `torch.nn`

`nn.Module`是pytorch提供的神经网络类，如果想实现某个神经网络，只需集成nn.Module，在初始化中定义模型结构和参数，在函数forward()中编写神经网络前向过程即可。

In [0]:
# 下面以一个由两个全连接成组成的感知机为例，介绍如何使用`nn.Module`构造模块化的神经网络。新建一个perception.py文件