<a href="https://colab.research.google.com/github/windrise/basictorch/blob/master/BasicTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 基本环境测试


In [0]:
from __future__ import print_function
import torch

In [0]:
 x = torch.Tensor(5,3)
print(x)


 2.2169e-35  0.0000e+00  4.4842e-44
 0.0000e+00         nan  0.0000e+00
 6.7947e+22  2.6079e+20  6.6383e-07
 1.0514e-05  8.5455e-07  4.1536e-08
 2.1253e-07  8.5013e-07  0.0000e+00
[torch.FloatTensor of size 5x3]



In [0]:
y = torch.rand(5,3)
print(y)
print(y.size)


 0.6284  0.5950  0.2834
 0.2547  0.9488  0.1956
 0.2709  0.5084  0.3546
 0.7146  0.9547  0.8258
 0.6737  0.4501  0.6427
[torch.FloatTensor of size 5x3]

<built-in method size of torch.FloatTensor object at 0x7f1e33021708>


## GPU

In [0]:
import tensorflow as tf
tf.test.gpu_device_name() 

'/device:GPU:0'

In [0]:
!nvidia-smi

Fri Jan  3 06:07:38 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.44       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [0]:
import torch
torch.cuda.is_available()

True

In [0]:
!python -V

Python 3.6.9


## 操作系统信息

In [0]:
!sudo lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic


## 查看cuda版本

In [0]:
!cat /usr/local/cuda/version.txt

CUDA Version 10.0.130


In [0]:
!ls

sample_data


## python

### 变量与对象
对象：内存中存储数据的实体，有明确的类型。一切皆是对象，函数也是对象。  
变量：指向对象的指针，对对象的引用。变量没有类型

In [0]:
# 深浅拷贝
'''
拷贝：原则上就是把数据分离出来，复制其数据，并以后修改互不影响。
先看一个非拷贝的例子
=赋值：数据完全共享（=赋值是在内存中指向同一个对象，如果是可变(mutable)类型，比如列表，修改其中一个，另一个必定改变
如果是不可变类型(immutable),比如字符串，修改了其中一个，另一个并不会变）
'''
import copy
a = [1, 2, [1,2]]
# 直接复制前后没有隔离   共享内存  地址相同
b = a
# 浅拷贝  数据半共享   只成功拷贝第一层
c = copy.copy(a)
d = a[:]
# 深拷贝  前后两个变量完全隔离  数据完全不共享
e = copy.deepcopy(a)
a.append(3)
a[2].append(3)
a,b,c,d,e

([1, 2, [1, 2, 3], 3],
 [1, 2, [1, 2, 3], 3],
 [1, 2, [1, 2, 3]],
 [1, 2, [1, 2, 3]],
 [1, 2, [1, 2]])

### 作用域

### 高阶函数
高阶函数指的是 接受函数作为输入或输出的函数。  
对于python而言，函数是一等对象，既可以赋值给变量、添加到集合中、传参到函数中，也可以作为函数的返回值。  
变量即为对对象的引用。 

### **迭代器和生成器**
> iter(),next(),yield  
> list,dict,set

## 常用工具  
> 版本管理git&github
> python调试器： pdb
> 网页可视化： jupyter
> 分屏工具： Terminator
> 任务托管： Screen 
> 任务后台执行： &nohup

## Tensor

### 数据类型

In [0]:
import torch


In [7]:
# 创建新的Tensor, 默认是torch.FloatTensor类型
a = torch.Tensor(2,2)
a 
#a.type()  #'torch.FloatTensor'

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])

In [9]:
# 使用int()，float()，double()等直接进行数据类型的转换
b = a.double()
b

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]], dtype=torch.float64)

In [13]:
# 使用type()函数
c = a.type(torch.DoubleTensor)
c

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]], dtype=torch.float64)

In [14]:
# 使用type_as()函数
d = a.type_as(b)
d

tensor([[1.7791e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]], dtype=torch.float64)

### Tensor的创建和维度查看

* 基础Tensor函数 torch.Tensor(2,2) #(2,2)每一维大小 
* 指定类型 torch.DoubleTensor(2,2)  
* 使用Python的list序列 torch.Tensor([[1,2],[3,4]]) 
* 默认值为0 torch.zeros(2,2)
* 默认值为1 torch.ones(2,2)
* 对角张量 torch.eye(2,2)
* 随机张量 torch.randn(2,2)
* 随机排列张量 torch.randperm(4）

> torch.arange(start,end,step)函数，从start到end,间距为step,一维向量
> torch.linspace(start,end,steps)函数，从start到end,一共steps份，一维向量  
> torch.randperm(num)生成长度为num的随机排列向量  
> pytorch 0.4中增加了torch.tensor()方法，参数可以为Python的list，Numpy的ndarray等

In [19]:
f = torch.eye(2,3)
f

tensor([[1., 0., 0.],
        [0., 1., 0.]])

查看Tensor的维度
> Tensor.shape或者size()函数可以查看 Tensor每一维大小  
查看Tensor的元素总个数
> Tensor.numel()或者Tensor.nelement()函数

### Tensor的组合与分块 
组合： torch.cat(),torch.stack()  
指沿着已有的数据的某一维度进行拼接，其他维度保持一致  
分块： torch.chunk(),torch.split()  
指